# This file manages the "New Issue" page configuration

blank_issues_enabled: true
contact_links:
  - name: ğŸ Report a bug
    url: .github/ISSUE_TEMPLATE/bug_report.md
    about: Use this template to report a problem with the current code.
  - name: â“ Ask a question
    url: https://github.com/ReKindleOS/your-repo-name/discussions/new?category=q-a
    about: Ask and answer questions about the project.
  - name: ğŸ›‘ DO NOT USE FOR ROADMAP FEATURES
    url: https://github.com/ReKindleOS/your-repo-name/blob/main/.github/ISSUE_TEMPLATE/feature_suggestion.md
    about: This link is for reference only. Feature ideas are reserved for collaborators.
