name = "rekindle-tmdb"
main = "worker.js"
compatibility_date = "2024-12-05"

[vars]
# Leave this empty.
# You will upload the key securely using the command line:
# npx wrangler secret put TMDB_API_KEY
